### ISSUE TITLE
EXC_BAD_ACCESS in -[RoutingConnection setHeadersForResponse:isError:]

### ISSUE THREAD

**Issue by ndouglas** [mattstevens/RoutingHTTPServer#13]
I encountered a crash (just once) when the local device disappeared from the network in the middle of responding to a request:

```
    #0  0x00007fff909760dd in objc_msgSend ()
    #1  0x0000000108f42223 in -[RoutingConnection setHeadersForResponse:isError:] at /Users/ndouglas/Projects/DEVONthink-Sync-Plugin-2/Sync/External/RoutingHTTPServer/Source/RoutingConnection.m:91
    #2  0x0000000108f42758 in -[RoutingConnection preprocessResponse:] at /Users/ndouglas/Projects/DEVONthink-Sync-Plugin-2/Sync/External/RoutingHTTPServer/Source/RoutingConnection.m:110
    #3  0x0000000108e97039 in -[HTTPConnection sendResponseHeadersAndBody] at /Users/ndouglas/Projects/DEVONthink-Sync-Plugin-2/Sync/External/RoutingHTTPServer/External/CocoaHTTPServer/Core/HTTPConnection.m:1243
    #4  0x0000000108e95f87 in -[HTTPConnection replyToHTTPRequest] at /Users/ndouglas/Projects/DEVONthink-Sync-Plugin-2/Sync/External/RoutingHTTPServer/External/CocoaHTTPServer/Core/HTTPConnection.m:1025
    #5  0x0000000108e9b62a in -[HTTPConnection socket:didReadData:withTag:] at /Users/ndouglas/Projects/DEVONthink-Sync-Plugin-2/Sync/External/RoutingHTTPServer/External/CocoaHTTPServer/Core/HTTPConnection.m:2199
    #6  0x0000000108f3b553 in __37-[GCDAsyncSocket completeCurrentRead]_block_invoke at /Users/ndouglas/Projects/DEVONthink-Sync-Plugin-2/Sync/External/RoutingHTTPServer/External/CocoaHTTPServer/Vendor/CocoaAsyncSocket/GCDAsyncSocket.m:5039
    #7  0x00000001008412bb in _dispatch_call_block_and_release ()
    #8  0x000000010083bd43 in _dispatch_client_callout ()
    #9  0x000000010083ffb3 in _dispatch_queue_drain ()
    #10 0x0000000100841fc0 in _dispatch_queue_invoke ()
    #11 0x000000010083ef5e in _dispatch_root_queue_drain ()
    #12 0x0000000100850cd0 in _dispatch_worker_thread3 ()
    #13 0x00007fff89d296cb in _pthread_wqthread ()
    #14 0x00007fff89d274a1 in start_wqthread ()
    Enqueued from GCDAsyncSocket (Thread 368)Queue : GCDAsyncSocket (serial)
    #0  0x000000010083dc92 in _dispatch_barrier_async_f_slow ()
    #1  0x0000000108f3b41e in -[GCDAsyncSocket completeCurrentRead] at /Users/ndouglas/Projects/DEVONthink-Sync-Plugin-2/Sync/External/RoutingHTTPServer/External/CocoaHTTPServer/Vendor/CocoaAsyncSocket/GCDAsyncSocket.m:5037
    #2  0x0000000108f3a3bb in -[GCDAsyncSocket doReadData] at /Users/ndouglas/Projects/DEVONthink-Sync-Plugin-2/Sync/External/RoutingHTTPServer/External/CocoaHTTPServer/Vendor/CocoaAsyncSocket/GCDAsyncSocket.m:4812
    #3  0x0000000108f38736 in -[GCDAsyncSocket maybeDequeueRead] at /Users/ndouglas/Projects/DEVONthink-Sync-Plugin-2/Sync/External/RoutingHTTPServer/External/CocoaHTTPServer/Vendor/CocoaAsyncSocket/GCDAsyncSocket.m:4002
    #4  0x0000000108f37e49 in __79-[GCDAsyncSocket readDataToData:withTimeout:buffer:bufferOffset:maxLength:tag:]_block_invoke at /Users/ndouglas/Projects/DEVONthink-Sync-Plugin-2/Sync/External/RoutingHTTPServer/External/CocoaHTTPServer/Vendor/CocoaAsyncSocket/GCDAsyncSocket.m:3907
    #5  0x00000001008412bb in _dispatch_call_block_and_release ()
    #6  0x000000010083bd43 in _dispatch_client_callout ()
    #7  0x000000010083ffb3 in _dispatch_queue_drain ()
    #8  0x0000000100841fc0 in _dispatch_queue_invoke ()
    #9  0x000000010083ef5e in _dispatch_root_queue_drain ()
    #10 0x0000000100850cd0 in _dispatch_worker_thread3 ()
    #11 0x00007fff89d296cb in _pthread_wqthread ()
    #12 0x00007fff89d274a1 in start_wqthread ()
```

Relevant method:

```
    - (void)setHeadersForResponse:(HTTPMessage *)response isError:(BOOL)isError {
        [http.defaultHeaders enumerateKeysAndObjectsUsingBlock:^(id field, id value, BOOL *stop) {
            [response setHeaderField:field value:value];
        }];
        ....
    }
```

Limited messing around in the debugger: 

```
    (lldb) po http.defaultHeaders
    error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=EXC_I386_GPFLT).
    The process has been returned to the state before expression evaluation.
    (lldb) po http
    0x0000600000194500
```

It's entirely possible that it's something that I'm doing, i.e. shutting off the server too abruptly or something, so feel free to assume I'm a dangerous idiot :-).  

I can show you any relevant code you'd like to see.

**Comment by ndouglas** [comment]
Ah, I figure I wasn't closing the existing connections correctly, so I did that a little more carefully -- I'll mark this closed pending some proof that I'm not an idiot.
